### ISSUE TITLE
java.lang.IllegalArgumentException: Spark DataType 'decimal(19,0)' could not be mapped to a corresponding DynamoDB data type.

### ISSUE THREAD

**Issue by lepirlouit** [audienceproject/spark-dynamodb#14]
I gt this error :

` java.lang.IllegalArgumentException: Spark DataType 'decimal(19,0)' could not be mapped to a corresponding DynamoDB data type.
	at com.audienceproject.spark.dynamodb.rdd.TypeConversion$.apply(TypeConversion.scala:48)
	at com.audienceproject.spark.dynamodb.rdd.ScanPartition$$anonfun$com$audienceproject$spark$dynamodb$rdd$ScanPartition$$typeConversions$1.applyOrElse(ScanPartition.scala:42)
	at com.audienceproject.spark.dynamodb.rdd.ScanPartition$$anonfun$com$audienceproject$spark$dynamodb$rdd$ScanPartition$$typeConversions$1.applyOrElse(ScanPartition.scala:41)
`

Couldn't say which data I have in my table that causes this issue.

**Comment by lepirlouit** [comment]
I had this issue because my table contains BigDecimal numbers
