### ISSUE TITLE
Dynamo DB Connector configuration

### ISSUE THREAD

**Issue by venkatwilliams** [audienceproject/spark-dynamodb#38]
Where do we specify DynamoDB Connector Details.  Like AWS Credentials and ARN name and other details..
val dynamoDf = spark.read.dynamodb("SomeTableName") 

`19/09/18 12:07:06 INFO DefaultSource: Using Guava version 16.0.1
Exception in thread "main" java.lang.NoClassDefFoundError: com/amazonaws/services/dynamodbv2/AmazonDynamoDBClientBuilder
	at com.audienceproject.spark.dynamodb.connector.DynamoConnector$$anonfun$getDynamoDBClient$2.apply(DynamoConnector.scala:49)
	at com.audienceproject.spark.dynamodb.connector.DynamoConnector$$anonfun$getDynamoDBClient$2.apply(DynamoConnector.scala:52)
	at scala.Option.getOrElse(Option.scala:121)
`

**Comment by cosmincatalin** [comment]
Hi @venkatwilliams, configuration options are listed in the [READ.me](https://github.com/audienceproject/spark-dynamodb/blob/master/README.md).

However, it seems that you've hit an issue around Guava. The Guava dependency is a common pain here. We will try to fix that.

I will close this, but please reopen if you feel that I have not completely answered your questions.

Ref: https://github.com/audienceproject/spark-dynamodb/issues/35

**Comment by venkatwilliams** [comment]
@cosmincatalin I have included Guava dependency in my project but still I am hitting the same issue. 
`19/09/18 17:23:51 INFO DefaultSource: Using Guava version 14.0.1
Exception in thread "main" java.lang.NoClassDefFoundError: com/amazonaws/client/builder/AwsSyncClientBuilder
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.audienceproject.spark.dynamodb.connector.DynamoConnector$$anonfun$getCredentials$1.apply(DynamoConnector.scala:62)
	at com.audienceproject.spark.dynamodb.connector.DynamoConnector$$anonfun$getCredentials$1.apply(DynamoConnector.scala:60)`
Other thing I want to check is If trying to connect Dynamo DB from my Laptop and run Spark Driver program where do we specify AWS Credentials..

**Comment by cosmincatalin** [comment]
I don't think we provide an option for using AWS keys, if that's what you want. We use the default credentials chain https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default
