### ISSUE TITLE
Write binary column types as output

### ISSUE THREAD

**Issue by sb2nov** [audienceproject/spark-dynamodb#41]
I see this error when trying to write out a binary column type. 

```
19/11/26 19:19:48 WARN TaskSetManager: Lost task 0.0 in stage 3.0 (TID 2, 192.168.208.164, executor 1): scala.MatchError: BinaryType (of class org.apache.spark.sql.types.BinaryType$)
	at com.audienceproject.spark.dynamodb.connector.TableConnector.$anonfun$updateItems$5(TableConnector.scala:166)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at com.audienceproject.spark.dynamodb.connector.TableConnector.$anonfun$updateItems$4(TableConnector.scala:164)
	at com.audienceproject.spark.dynamodb.connector.TableConnector.$anonfun$updateItems$4$adapted(TableConnector.scala:161)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at com.audienceproject.spark.dynamodb.connector.TableConnector.updateItems(TableConnector.scala:161)
	at com.audienceproject.spark.dynamodb.rdd.DynamoWriteRelation.$anonfun$update$1(DynamoWriteRelation.scala:51)
	at com.audienceproject.spark.dynamodb.rdd.DynamoWriteRelation.$anonfun$update$1$adapted(DynamoWriteRelation.scala:51)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:935)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:935)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2101)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:411)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sb2nov** [comment]
when adding this from pyspark

**Comment by cosmincatalin** [comment]
Hi @sb2nov, thank you for reporting. We'll try to look at this as soon as possible.

**Comment by sb2nov** [comment]
@cosmincatalin thanks for the quick response. It was fixed once I tried to write out a bytearray and upgrade to the 1.0.0 release.
