### ISSUE TITLE
NPE when upgrading Spark-DynamoDB to 1.0.0

### ISSUE THREAD

**Issue by lucienfregosi** [audienceproject/spark-dynamodb#42]
Hi we are using your project (many thanks by the way) and we wanted to upgrade the connector with the 1.0.0 version. 
Because of Guava we weren't able to test the connector locally (conflicts between our guava and yours). So 1.0.0 is a great news for us.
Sadly when I update the version, the code is not working anymore , I got an NPE.

`java.lang.NullPointerException: null
	at org.apache.spark.sql.catalyst.InternalRow.getString(InternalRow.scala:34)
	at com.audienceproject.spark.dynamodb.catalyst.JavaConverter$.convertRowValue(JavaConverter.scala:39)
	at com.audienceproject.spark.dynamodb.catalyst.JavaConverter$$anonfun$5.apply(JavaConverter.scala:71)
	at com.audienceproject.spark.dynamodb.catalyst.JavaConverter$$anonfun$5.apply(JavaConverter.scala:70)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.audienceproject.spark.dynamodb.catalyst.JavaConverter$.convertStruct(JavaConverter.scala:70)
	at com.audienceproject.spark.dynamodb.catalyst.JavaConverter$.convertRowValue(JavaConverter.scala:38)
	at com.audienceproject.spark.dynamodb.connector.TableConnector$$anonfun$putItems$1$$anonfun$apply$7.apply(TableConnector.scala:134)
	at com.audienceproject.spark.dynamodb.connector.TableConnector$$anonfun$putItems$1$$anonfun$apply$7.apply(TableConnector.scala:132)
	at scala.collection.immutable.List.foreach(List.scala:392)`

The data and the code are exactly the same the only thing which has changed is the connector version.
Our data are json based, some fields could be missing but we replace any null column with a null object. For example

| name | info |
| -- | -- |
| foo | `{"age":18, "address" : "..."}` |
| bar | `null` |

Becames

| name | info |
| -- | -- |
| foo     | `{"age":18, "address" : "..."}` |
|bar     | `{"age": null, "address" : null}` |

If you have any clue about how can we make the 1.0.0 working for our case, it would be great :)

**Comment by cosmincatalin** [comment]
Hi @lucienfregosi, on the top of my head, DynamoDB does not support blank or null values. If you don't have a non-empty value for the address, it must not be in the dataset. Can you please confirm?

**Comment by cosmincatalin** [comment]
So if I understand correctly, the problem arises when you are trying to persist the data to DyanmoDB, right?
Also, the `info` field is actually a String, right?
Better yet, can you do a `printSchema()` on your dataframe just before you try to write it to DyanmoDB, and then paste it here?

**Comment by lucienfregosi** [comment]
Yes but it worked with the previous version of the connector.
The info field is more a struct or an array<struct>

Results of the print Schema :

```
 |-- localizedData: struct (nullable = true)
 |    |-- address: struct (nullable = true)
 |    |    |-- postCodes: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- postCodeTypeCode: string (nullable = true)
 |    |    |    |    |-- postCodeValue: string (nullable = true)
 |    |    |-- postOfficeBox: string (nullable = true)
 |    |    |-- streetName: string (nullable = true)
 |    |    |-- streetNumber: string (nullable = true)
 |    |    |-- complementaryStreetName: string (nullable = true)
 |    |    |-- town: string (nullable = true)
 |    |-- communicationChannels: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- typeCode: string (nullable = true)
 |    |    |    |-- value: string (nullable = true)
 |    |-- alphabetCode: string (nullable = true)
 |    |-- localizedLegalData: struct (nullable = true)
 |    |    |-- companyName: string (nullable = true)
 |    |    |-- secondaryNames: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- alternativeName: string (nullable = true)
 |    |    |    |    |-- nameTypeCode: string (nullable = true)
```

Thanks :)

**Comment by jacobfi** [comment]
This is being fixed with release 1.0.1

**Comment by jacobfi** [comment]
Version 1.0.1 is now on Maven Central.

**Comment by lucienfregosi** [comment]
Thanks it works well with 1.0.1 :D
Many thanks for your work
